### PR TITLE
updates, updates, updates

### PR DESCRIPTION
**Pull request by glaszig**
- updated everything
- made the test suite be green
- refactored a few things
- fixed a thing here and there
- made everything run on ruby >= 2.4
- added a dark mode

dark
light

### CODE REVIEW

**Comment by benschwarz** [comment]
This is great @glaszig! Thank you for your contributions. Glad you’ve found this old project useful in some way. 👍

As a final step, would you mind adding a GitHub actions runner for the tests?

**Comment by benschwarz** [comment]
(Otherwise, reviewed and happy to accept this PR)

**Comment by glaszig** [comment]
> adding a GitHub actions runner

done, looking good. but since ruby 2.3 reached eol [gh doesn't support it anymore](https://github.blog/changelog/2019-10-17-github-actions-removing-python-3-4-and-ruby-2-3-from-the-virtual-environments/) and 2.7 just came out yesterday.

**Comment by glaszig** [comment]
btw, this fixes #8, #9 and #5 as well.

**Comment by benschwarz** [comment]
Is this ready for final review and merge now, @glaszig?

**Comment by glaszig** [comment]
yes, please.

**Pull request merged**
