### PR TITLE
fix haml

### PR DESCRIPTION
**Pull request by glaszig**
version 1.1.0 is broken with haml 6 because it escapes html by default.

please release as 1.2.0.

i have a follow-up to support newer rubies.

### CODE REVIEW

**Comment by benschwarz** [comment]
Thanks for your continued maintenance work @glaszig 🙇‍♂️

Ready to merge?

**Comment by glaszig** [comment]
> Ready to merge?

ready.

**Comment by glaszig** [comment]
> please release as 1.2.0.

🙏

**Comment by benschwarz** [comment]
1.2.0 is out, thanks @glaszig!

**Pull request merged**
