### PR TITLE
upgrade ruby

### PR DESCRIPTION
**Pull request by glaszig**
**to be merged after #18**

- drop 2.5 and 2.6.
- lowest supported ruby is 2.7
- test on 3.0, 3.1, 3.2 and head
- ruby 3 does not ship webrick so add thin as dev dependency

### CODE REVIEW

**Comment by benschwarz** [comment]
Assuming Ruby 3.2 works, would you consider setting that in .ruby-version instead of 2.7?

**Comment by glaszig** [comment]
> would you consider setting that in .ruby-version instead of 2.7?

my approach is to use the lowest supported version for development and thus it's in `.ruby-version`. but please convince me otherwise... what's your approach?

**Comment by benschwarz** [comment]
@glaszig sounds like our preferences are opposite ends of the spectrum! Not to worry, I'm happy either way.

Generally when I'm upgrading runtime versions on a project, I'll update it to the latest stable / lts release because it'll have the longest longevity, and helps to establish that the latest version is supported (and well used in local development/test mode). 

Seeing as all versions are covered by the test suite it seems like a safe option without breaking old releases. Again, I'm happy either way as you've demonstrated great care for amnesia over the years!

**Comment by glaszig** [comment]
> Generally when I'm upgrading runtime versions on a project, I'll update it to the latest stable / lts release because it'll have the longest longevity, and helps to establish that the latest version is supported (and well used in local development/test mode).

thanks for the input. makes sense. i updated `.ruby-version`.

**Review by benschwarz — APPROVED** [review]
Thanks for your contributions!

**Pull request merged**
